name: Bicep -> ARM

on:
  # push:
  #   branches: [main]
  #   paths:
  #     # only run if bicep files changed
  #     - 'dev-environment/cu-sandbox/main.bicep'
  # We also want to be able to run this workflow manually from Github
  workflow_dispatch:

jobs:
  build:
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Build Bicep -> ARM
      #   run: python ./dev-environment/tools/build-arm.py

      - name: Build Bicep => ARM
        run: |
          az bicep build --file dev-environment/cu-sandbox/main.bicep --outfile dev-environment/cu-sandbox/azuredeploy.json

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add dev-environment/cu-sandbox/azuredeploy.json
          git commit -am "Rebuilt cu-sandbox ARM templates"
          git push
