name: 'Dev - App Build & Deploy'

on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'infra/**'
  #     - '**/ContosoUniversity - Infra.yml'
  #     - '**/README.md'
  # pull_request:
  #   branches: 
  #     - main
  #   paths-ignore:
  #     - 'infra/**'
# We also want to be able to run this manually from Github
  workflow_dispatch:

env:
  CONFIGURATION: release
  AZ_APP_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-app
  AZ_API_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-api

# To use OIDC enabled SPN with Azure
permissions:
  id-token: write

jobs:
  build:
    name: 'Build APP & API'
    environment: dev
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore
      run: dotnet restore src/ContosoUniversity.sln
    
    - name: Build
      run: dotnet build src/ContosoUniversity.sln --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test src/ContosoUniversity.Test/ContosoUniversity.Test.csproj --verbosity normal --logger trx --results-directory TestResults
      
    - name: Publish APP
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApp src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj

    - name: Publish API
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApi src/ContosoUniversity.API/ContosoUniversity.API.csproj
    
    - name: Upload APP results
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: PublishApp
    
    - name: Upload API results
      uses: actions/upload-artifact@v3
      with:
        name: api
        path: PublishApi
  
  release:
    needs: build

    name: 'Deploy APP & API'
    environment: dev
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772

    steps:
      - name: Download APP Artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: app-artifact
      
      - name: Download API Artifact
        uses: actions/download-artifact@v3
        with:
          name: api
          path: api-artifact
      
      - name: Variable Substitution API
        uses: microsoft/variable-substitution@v1
        with:
          files: api-artifact/appsettings.json
        env:
          ConnectionStrings.ContosoUniversityAPIContext: ${{ secrets.AZURE_CONTOSO_CONN_STRING }}
          ApplicationInsights.ConnectionString: ${{ secrets.AZURE_CONTOSO_APP_INSIGHTS }}
      
      - name: Variable Substitution APP
        uses: microsoft/variable-substitution@v1
        with:
          files: app-artifact/appsettings.json
        env:
          Api.Address: https://${{ env.AZ_API_NAME }}.azurewebsites.net/
          ApplicationInsights.ConnectionString: ${{ secrets.AZURE_CONTOSO_APP_INSIGHTS }}
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ vars.AZURE_GHA_CLIENT_ID }}
    
      - name: Deploy API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZ_API_NAME }}
          package: api-artifact
          # it uses ZIP Deploy
      
      - name: Deploy APP
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZ_APP_NAME }}
          package: app-artifact