name: 'DEV - Solution - Deploy'

on:
  # We also want to be able to run this workflow manually from Github
  workflow_dispatch:
  
  # Enabling this workflow to be reusable
  workflow_call:

env:
  CONFIGURATION: release
  AZ_APP_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-app
  AZ_API_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-api

# To use OIDC enabled SPN with Azure
permissions:
  id-token: write

jobs:
  build:
    name: 'Build'
    environment: dev
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore solution
        run: dotnet restore src/ContosoUniversity.sln
      
      - name: Build solution
        run: dotnet build src/ContosoUniversity.sln --configuration ${{ env.CONFIGURATION }} --no-restore
      
      - name: Test solution
        run: dotnet test src/ContosoUniversity.Test/ContosoUniversity.Test.csproj --verbosity normal --logger trx --results-directory TestResults
        
      - name: Publish APP
        run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApp src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj

      # Publish API code in PublishApi/ folder
      - name: Publish API
        run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApi src/ContosoUniversity.API/ContosoUniversity.API.csproj

      # Uploads the PublishApp/ and PublishApi/ folders as (Zip) artifacts
      - name: Upload APP artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: PublishApp
      
      - name: Upload API artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: PublishApi
  
  deploy-api:
    needs: build
    name: 'Deploy API'
    environment: dev
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772

    steps:
      # Downloads the artifact ZIP and extracts it to the api-artifact/ folder
      - name: Download API artifacts
        uses: actions/download-artifact@v3
        with:
          name: api
          path: api-artifact
    
      - name: Substitutions API
        uses: microsoft/variable-substitution@v1
        with:
          files: api-artifact/appsettings.json
        env:
          ConnectionStrings.ContosoUniversityAPIContext: ${{ secrets.AZURE_CONTOSO_CONN_STRING }}
          ApplicationInsights.ConnectionString: ${{ secrets.AZURE_CONTOSO_APP_INSIGHTS }}
      
      - name: Azure Login with OIDC
        uses: Azure/login@v1
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ vars.AZURE_GHA_CLIENT_ID }}
    
      - name: Deploy@v3 API
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZ_API_NAME }}
          package: api-artifact

  deploy-app:
    needs: build
    name: 'Deploy APP'
    environment: dev
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772

    steps:
      - name: Download APP artifacts
        uses: actions/download-artifact@v3
        with:
          name: app
          path: app-artifact
      
      - name: Substitutions APP
        uses: microsoft/variable-substitution@v1
        with:
          files: app-artifact/appsettings.json
        env:
          Api.Address: https://${{ env.AZ_API_NAME }}.azurewebsites.net/
          ApplicationInsights.ConnectionString: ${{ secrets.AZURE_CONTOSO_APP_INSIGHTS }}
      
      - name: Azure Login with OIDC
        uses: Azure/login@v1
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ vars.AZURE_GHA_CLIENT_ID }}

      - name: Deploy@v3 APP
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZ_APP_NAME }}
          package: app-artifact