name: 'DEV - Merge to main > Deploy'

on:
  # Automatic trigger
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'infra/**'

  # Enable manual run from Github UI (in repo / Actions tab)
  workflow_dispatch:

# Required to use OIDC enabled SPN with Azure
permissions:
  id-token: write

jobs:
  infra:
    name: 'Infra'
    uses: embergershared/dev-ex-app/.github/workflows/dev_azure-infra.yml@main
    secrets: inherit

  apps:
    needs: infra
    name: 'Solution'
    uses: embergershared/dev-ex-app/.github/workflows/dev_app-build-deploy.yml@main
    secrets: inherit
