name: DevExDay-Infra-DevEnv

on:
  # Automatic trigger
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'infra/**'
      
  # Enable manual run from Github UI (in repo / Actions tab)
  workflow_dispatch:

# To use OIDC enabled SPN with Azure
permissions:
  id-token: write

env:
  AZ_ENVIRONMENT_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}
  AZ_LOCATION: ${{ vars.AZURE_LOCATION }}
  AZ_APP_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-app
  AZ_API_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-api
  AZ_SQL_SERVER_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
  AZ_APP_PASSWORD: ${{secrets.AZURE_APP_PASSWORD}}

jobs:
  infra:
    name: 'Deploy Infrastructure'
    # environment: dev
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772

    steps:
    - uses: actions/checkout@v2

    # - name: Azure Login
    #   uses: Azure/login@v1.4.4
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Login
      uses: Azure/login@v1
      with:
        tenant-id: ${{ vars.AZURE_TENANT_ID }} # 'bed3f66f-00c5-402e-8f75-44abca53e730'
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }} # 'a73ced30-c712-4405-8828-67a833b1e39a'
        client-id: ${{ vars.AZURE_GHA_CLIENT_ID }} # 'd8bf5cdc-b42f-485e-9863-cff285eaae5c' #

    # - name: Deploy Template
    #   uses: Azure/arm-deploy@v1.0.8
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     region: ${{ env.AZ_LOCATION }}
    #     template: infra/main.bicep
    #     deploymentMode: Incremental
    #     deploymentName: 'gh-actions'
    #     parameters: environmentName=${{ env.AZ_ENVIRONMENT_NAME }} location=${{ env.AZ_LOCATION }} apiServiceName=${{ env.AZ_API_NAME }} webServiceName=${{ env.AZ_APP_NAME }} sqlAdminPassword=${{ env.AZ_SQL_SERVER_PASSWORD }} appUserPassword=${{ env.AZ_APP_PASSWORD }} resourceGroupName="rg-use2-912772-s1-${{ env.AZURE_ENVIRONMENT_NAME }}-01" # 'rg-use2-912772-s1-devexdays-app-01'
    #     failOnStdErr: false