# This workflow is a test. It creates a Github issue each time an issue is closed.
# It uses the `gh` client with a dedicated Access Token with read/write issues permissions.

name: Move assigned card
on:
  issues:
    types:
      - closed

env:
  GH_TOKEN: ${{ secrets.GHA_TOKEN_ISSUE }}

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    # runs-on:
    #   # We use a GH organization Self-hosted runner wired in the Private VNET
    #   group: embergershared
    #   labels: 912772
    steps:
      - name: Create "My new issue"
        run: |
          gh issue create --title "My new issue" --body "Here are more details."