# This workflow is a test. It creates a Github issue each time an issue is closed.
# It uses the `gh` client with a dedicated Access Token with read/write issues permissions.

name: Create an issue on edited issue
on:
  issues:
    types:
      - edited
  # We also want to be able to run this workflow manually from Github
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  move-assigned-card:
    name: Create an issue when an issue is edited
    runs-on: ubuntu-latest
    # runs-on:
    #   # We use a GH organization Self-hosted runner wired in the Private VNET
    #   group: embergershared
    #   labels: 912772
    steps:
      # For 'gh' to work, we need to operate in a git repo
      - name: Checkout
        uses: actions/checkout@v2

      - name: List issues
        run: |
          echo "List issues:"
          gh issue list
  
      - name: Show edited issue
        run: |
          echo "Show edited issue:"
          gh issue view ${{ github.event.issue.number }}
