# This workflow is a test. It creates a Github issue each time an issue is closed.
# It uses the `gh` client with a dedicated Access Token with read/write issues permissions.

name: Create an issue on closed issue
on:
  issues:
    types:
      - closed
  # We also want to be able to run this workflow manually from Github
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  move-assigned-card:
    name: Create an issue when an issue is closed
    runs-on: ubuntu-latest
    # runs-on:
    #   # We use a GH organization Self-hosted runner wired in the Private VNET
    #   group: embergershared
    #   labels: 912772
    steps:
      - name: Check where we are
        run: |
          echo "=============================="
          echo "Show where we execute (pwd):"
          pwd
          ls -al
          echo
          echo "=============================="
          echo "Check the login (gh auth status):"
          gh auth status
          echo
          echo "=============================="
          echo "See our repos (gh repo list):"
          gh repo list

      - name: List issues
        run: |
          echo "List issues:"
          gh --version
          gh issue list
  
      - name: Create "My new issue"
        run: |
          echo "Create the new issue:"
          gh issue create --title "My new issue" --body "Here are more details."
