name: 'Dev infra deployment'

on:
  # Automatic trigger
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'infra/**'

  # Enable manual run from Github UI (in repo / Actions tab)
  workflow_dispatch:

# To use OIDC enabled SPN with Azure
permissions:
  id-token: write

env:
  AZ_ENVIRONMENT_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}
  AZ_LOCATION: ${{ vars.AZURE_LOCATION }}
  AZ_APP_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-app
  AZ_API_NAME: ${{ vars.AZURE_ENVIRONMENT_NAME }}-api
  AZ_SQL_SERVER_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
  AZ_APP_PASSWORD: ${{secrets.AZURE_APP_PASSWORD}}

jobs:
  infra:
    name: 'Deploy Infra with bicep'
    environment: dev
    runs-on:
      # We use a GH organization Self-hosted runner wired in the Private VNET
      group: embergershared
      labels: 912772

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: Azure/login@v1
      with:
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ vars.AZURE_GHA_CLIENT_ID }}

    - name: Deploy bicep Template
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        region: ${{ env.AZ_LOCATION }}
        template: infra/main.bicep
        # deploymentMode: Incremental
        deploymentName: 'gh-actions'
        parameters: environmentName=${{ env.AZ_ENVIRONMENT_NAME }} location=${{ env.AZ_LOCATION }} resourceGroupName="rg-use2-912772-s1-${{ env.AZ_ENVIRONMENT_NAME }}-01" #apiServiceName=${{ env.AZ_API_NAME }} webServiceName=${{ env.AZ_APP_NAME }} sqlAdminPassword=${{ env.AZ_SQL_SERVER_PASSWORD }} appUserPassword=${{ env.AZ_APP_PASSWORD }}  #"rg-use2-912772-s1-${{ env.AZURE_ENVIRONMENT_NAME }}-01"
        failOnStdErr: false

    # - name: az cli version
    #   run: az version

    # - name: az account infos
    #   run: |
    #     az account show
    #     echo "Subsc Name: $(az account show --query "name" -o tsv)"
    #     echo "Subsc   Id: $(az account show --query "id" -o tsv)"
    #     echo "SPN Name  : $(az account show --query "user.name" -o tsv)"